version: '3.1'
services:
  db:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - "${PWD}/mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    user: ${CURRENT_UID}

  dbadmin:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
     - db
